### ISSUE TITLE
JSXDOM is not a function

### ISSUE THREAD

**Issue by callumlocke** [vjeux/jsxdom#1]
The JSX transpiler bundled with Babel transforms this:

``` jsx
/** @jsx JSXDOM */
console.log(<div>test</div>);
```

to this:

``` js
/** @jsx JSXDOM */
console.log(JSXDOM(
  'div',
  null,
  'test'
));
```

But when I try to run this (with jsxdom.js included in the page), I get the error `JSXDOM is not a function`.

It looks like JSXDOM is an object with lots of properties that are functions, but the JSX compiler is not expecting this.

Has the JSX compiler changed since you wrote this?

**Comment by rdooh** [comment]
I'm having this issue too - what was the solution?  using language-babel 0.15.5 in Atom...

**Comment by callumlocke** [comment]
It looked like this project is unmaintained, so I wrote my own: https://github.com/callumlocke/plain-jsx

``` js
/** @jsx plainJSX */
```

It's just this little function: https://github.com/callumlocke/plain-jsx/blob/master/index.js

**Comment by rdooh** [comment]
nice!
